on:
  workflow_dispatch:
  push:
    branches:
    - main
    
jobs:
  build_release:
    name: build release
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v3.3.0
    - name: build
      run: ./build/build-unix.sh
    - name: read version num
      id: rv
      uses: shaneapowell/github-tweak-the-json@v1
      with:
        action: read
        filename: ./plugin/manifest.json
        field: version
    - name: release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "elephant.fda"
        tag: ${{ steps.rv.outputs.value }}
        token: ${{ secrets.GITHUB_TOKEN }}
